function Hd = BandPass900to1300Hz
%BANDPASS900TO1300HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 29-Apr-2018 20:35:39

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 41667;  % Sampling Frequency

Fstop1 = 1;               % First Stopband Frequency
Fpass1 = 900;             % First Passband Frequency
Fpass2 = 1300;            % Second Passband Frequency
Fstop2 = 1400;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
