function Hd = BandPassFilterTest
%BANDPASSFILTERTEST Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 23-Apr-2018 11:12:36

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 40000;  % Sampling Frequency

Fstop1 = 350;             % First Stopband Frequency
Fpass1 = 400;             % First Passband Frequency
Fpass2 = 2000;            % Second Passband Frequency
Fstop2 = 2050;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
