s = serial('COM51', ... 
    'BaudRate',921600, ...
    'DataBits', 8, ...
    'StopBits', 1, ...
    'Parity', 'none', ...
    'Terminator', 'CR/LF' ...
    );

fopen(s);



% s = serial('COM30', ... 
%     'BaudRate',115200, ...
%     'DataBits', 8, ...
%     'StopBits', 1, ...
%     'Parity', 'none', ...
%     'Terminator', 'CR/LF' ...
%     );
% 
% fopen(s);
